version: '3'

networks:
  kafka-sendmail-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 1.249.1.0/24

services:
  kafka-sendmail:
    restart: always
    tty: true
    build: .
    command: sh ./run.sh
    depends_on:
      - zookeeper
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka://1.249.1.3:9092
      - KAFKA_BOOSTRAP_SERVER_NAME=1.249.1.3
      - KAFKA_BOOSTRAP_SERVER_PORT=9092

    ports:
      - "38084:80"
      - "38000:8000"


    networks:
      kafka-sendmail-network:
        ipv4_address: 1.249.1.10

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "32181:2181"
    networks:
      kafka-sendmail-network:
        ipv4_address: 1.249.1.2

  kafka:
    image: wurstmeister/kafka
    # build: .
    ports:
      - "9092"
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      PORT_COMMAND: "docker port $$(hostname) 9092/tcp | cut -d: -f2"
      KAFKA_ADVERTISED_HOST_NAME: 1.249.1.3
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://_{HOSTNAME_COMMAND}:_{PORT_COMMAND},INSIDE://1.249.1.3:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://1.249.1.3:9092
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      # KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://_{HOSTNAME_COMMAND}:_{PORT_COMMAND}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      kafka-sendmail-network:
        ipv4_address: 1.249.1.3